# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.firefox.options import Options

import time
import pyautogui

from selenium.webdriver.common.action_chains import ActionChains

import yaml

with open('marketplaceAd.yaml') as stream:
  adInfo = yaml.load(stream)

with open('dump.yaml') as stream:
  oldTitles = yaml.load(stream)

options = Options()
options.binary_location = adInfo['firefox']
driver = webdriver.Firefox(executable_path=adInfo['geckoDriver'], firefox_options=options)

email = adInfo['loginEmail']
password = adInfo['loginPassword']

adRemove = "//div[@aria-label=\'" + str(adInfo['Title']) + "\']"

def login():
  driver.get("https://www.facebook.com/")
  driver.set_window_size(1527, 869)
  driver.find_element(By.ID, "email").send_keys(email)
  driver.find_element(By.ID, "pass").click()
  driver.find_element(By.ID, "pass").send_keys(password)
  driver.find_element(By.NAME, "login").click()


def gotoMarketplace():
  try:
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.LINK_TEXT, "Marketplace"))
    )
    element.click()

    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.LINK_TEXT, "Your Account"))
    )
    element.click() 

  except:
    print("oops")

def removeAd():
  time.sleep(1)
  driver.find_element_by_xpath(adRemove).click()

  try:
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".oqcyycmt:nth-child(2) > .oajrlxb2"))
    )
    element.click()

    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".rq0escxv:nth-child(1) > .rq0escxv:nth-child(1) > .oajrlxb2 > .rq0escxv"))
    )
    element.click()

  except:
    print("oops2")

  removePrevTitle()



def removePrevTitle():
  oldTitles['previousTitles'].remove(adInfo['Title'])
  with open("dump.yaml", 'w') as stream:
    try:
      yaml.dump(oldTitles, stream)
    except:
      print("oops6")

login()
gotoMarketplace()
removeAd()