# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.firefox.options import Options

import time

from selenium.webdriver.common.action_chains import ActionChains

options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Firefox(executable_path=r'C:\Program Files (x86)\geckodriver.exe', firefox_options=options)

#I made a list of all the possible elements for the Type of Page section, because whatever I tried wouldn't work. 
adType = ["jsc_c_x", "jsc_c_y", "jsc_c_w", "jsc_c_z", "jsc_c_10", "jsc_c_11", "jsc_c_16", "jsc_c_14", "jsc_c_12", "jsc_c_13"]
adTypeElement = []

for x in range (len(adType)):
    adTypeElement.append(" ")


def login():
  driver.get("https://www.facebook.com/")
  driver.set_window_size(1527, 869)
  driver.find_element(By.ID, "email").send_keys("marhpe36@gmail.com")
  driver.find_element(By.ID, "pass").click()
  driver.find_element(By.ID, "pass").send_keys("HrbvK2piw410ofLm")
  driver.find_element(By.NAME, "login").click()

#I reordered, and rewrote most of this after lots of trial and error
def ad():
    try:
        element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".bp9cbjyn > .tojvnm2t .hu5pjgll"))
            )
        element.click()

        element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "div:nth-child(5) > .oajrlxb2 .gs1a9yip"))
            )
        element.click()
    except:
        print("oopsy")

#I made it get these variables earlyer, and keep them as variables
    try:
        Name = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "//label/div/div/input"))
            )

        Desc = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "//textarea"))
            )

    except:
        print("oops")
    

#then it trys to type f in all of the variables that I found out before with trial and error
    for x in range (len(adType)):
        try:
            adTypeElement[x] = WebDriverWait(driver, 0).until(
                EC.presence_of_element_located((By.ID, adType[x]))
                )
            adTypeElement[x].click()
            adTypeElement[x].send_keys("f")
#If the element that I type f in also creates this element, write it down, then click it
#this is in here because sometimes the other boxes(Title and description) share some of the previous variable names, and this element only pops up when you are in the right one
            try:
                element = WebDriverWait(driver, 1).until(
                    EC.presence_of_element_located((By.CSS_SELECTOR, "#\\31 92803624072087 .d2edcug0")))
            except:
                print("uh oh" + str(x))

            element.click()
        except:
            print("oops" + str(x))
    
    Desc.click()
    Desc.send_keys(Keys.BACK_SPACE,"Description")

    Name.click()
    Name.send_keys(Keys.BACK_SPACE, "Name of Page")

#I finnaly got the proper variable for this element. I had to go into the element add-on and try to reselect differnt variables at the "create page" box
#This is because there were like 5 overlapping vaiables that gave me an error when I tried to click it because it was aparently off screen
    try:
        element = WebDriverWait(driver, 1).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".ihqw7lf3:nth-child(3) > .rq0escxv:nth-child(2) > .rq0escxv"))
            )
        element.click()
    except:
        print("oop")


login()

ad()

#yay I fixed it and it workes every time now