# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.firefox.options import Options

import time

from selenium.webdriver.common.action_chains import ActionChains

options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Firefox(executable_path=r'C:\Program Files (x86)\geckodriver.exe', firefox_options=options)


def login():
  driver.get("https://www.facebook.com/")
  driver.set_window_size(1527, 869)
  driver.find_element(By.ID, "email").send_keys("marhpe36@gmail.com")
  driver.find_element(By.ID, "pass").click()
  driver.find_element(By.ID, "pass").send_keys("HrbvK2piw410ofLm")
  #I had to change this to find element by name because the ID changed every time
  driver.find_element(By.NAME, "login").click()

def post():

  try:
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".bp9cbjyn > .tojvnm2t .hu5pjgll"))
        )
    element.click()

    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".a8nywdso:nth-child(2) > div:nth-child(1) > .oajrlxb2:nth-child(1) .qzhwtbm6:nth-child(2) > .d2edcug0:nth-child(1)"))
        )
    element.click()

    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "div:nth-child(2) > .tojvnm2t .tv7at329 .hu5pjgll"))
        )
    element.click()

    path = "C:\\Users\\ephra\\OneDrive\\Pictures\\TestPhoto.png"

    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//input[@type='file']"))
        )
    element.send_keys(path)

    #Actions(driver).moveByOffset(200, 650).click()

    #element = WebDriverWait(driver, 10).until(
        #EC.presence_of_element_located((By.CSS_SELECTOR, ".k4urcfbm > .oajrlxb2 .rq0escxv > .d2edcug0 > .a8c37x1j"))
        #)
    #element.click()

    #driver.find_element(By.CSS_SELECTOR, ".k4urcfbm > .oajrlxb2 .rq0escxv > .d2edcug0 > .a8c37x1j").click()

  except:
    print("oops")

  #driver.switch_to_frame(0)

  time.sleep(1)
  
  for x in range(15):
    webdriver.ActionChains(driver).send_keys(Keys.TAB).perform()
  
  webdriver.ActionChains(driver).send_keys(Keys.ENTER).perform()






login()

post()